apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ketan02-git/project1.git
    targetRevision: dev
    path: helm/node-app
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
